UTORRENT_USER = ''
UTORRENT_PASS = ''
UTORRENT_URL = ''
UTORRENT_PORT = 0

SHOWS_JSON_FILE = 'shows.json'

UTORRENT_CREDENTIALS = {
    'url': UTORRENT_URL,
    'port': UTORRENT_PORT,
    'user': UTORRENT_USER,
    'password': UTORRENT_PASS
}
